version: "3"

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13

    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

    networks:
      - kittygram

  backend:
    image: ${DOCKERHUB_USERNAME}/kittygram_backend:latest

    env_file: .env

    depends_on:
      - db

    volumes:
      - static:/app/collected_static
      - media:/app/media

    networks:
      - kittygram

  frontend:
    image: ${DOCKERHUB_USERNAME}/kittygram_frontend:latest

    volumes:
      - static:/static

    networks:
      - kittygram

  gateway:
    image: ${DOCKERHUB_USERNAME}/kittygram_gateway:latest

    ports:
      - "80:80"

    volumes:
      - static:/static
      - media:/media
    depends_on:
      - backend
      - frontend

    networks:
      - kittygram

networks:
  kittygram:
    driver: bridge
